# Site settings
title: Wyatt Solutions
email: sales@wyattsolutions.com
url: https://github.com/Apress/mlops-lifecycle-toolkit
description: "Delivering innovative, custom technology solutions, including digital transformation, managed services, and expertise in cloud technologies like Azure Machine Learning. Specializing in automation and analytics, we are a botique, low-volume, high-value provider of digital transformation services for private equity firms.."
keywords: "Azure, data engineering, cloud services, digital transformation, data integration, data storage, data processing, data analytics, managed services, Azure Machine Learning, Databricks"
skills: "Digital Transformation - Managed Services - Cloud Solutions - Data Integration - Data Analytics"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: wyattsolutions

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0072C6 #80B3FF
  primary-rgb: "0,114,198" #"128,179,255"
  secondary: 002050 #FD6E8A
  secondary-dark: 001833 #A2122F

# Footer settings
footer:
  copyright: Wyatt Solutions Inc.
  location:
  social: Get a Quote
  credits: This site was built and hosted using open source

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Serving businesses
  - line: in North America and globally

# Credits content
credits: 'This site was custom built by Wyatt Solutions'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
